'use client';
import { Upload, Download, RotateCcw } from 'lucide-react';
import { useRef, useState } from 'react';

export default function ToolWorkspace({ kind }: { kind: string }) {
  const [file, setFile] = useState<File | null>(null); const [src, setSrc] = useState(''); const [out, setOut] = useState('');
  const [width, setWidth] = useState(0); const [height, setHeight] = useState(0); const [quality, setQuality] = useState(80); const input = useRef<HTMLInputElement>(null);
  function load(f: File) { if (!f.type.startsWith('image/')) return; setFile(f); const u = URL.createObjectURL(f); setSrc(u); const im = new Image(); im.onload = () => { setWidth(im.width); setHeight(im.height) }; im.src = u; setOut(''); }
  function process() { if (!file) return; if (kind === 'image-to-base64') { const r = new FileReader(); r.onload = () => setOut(String(r.result)); r.readAsDataURL(file); return; } const im = new Image(); im.onload = () => { const c = document.createElement('canvas'); c.width = width || im.width; c.height = height || im.height; const x = c.getContext('2d')!; if (kind === 'png-to-jpg' || kind === 'webp-to-jpg') { x.fillStyle = '#fff'; x.fillRect(0, 0, c.width, c.height); } x.drawImage(im, 0, 0, c.width, c.height); const type = kind === 'jpg-to-png' ? 'image/png' : (kind === 'png-to-jpg' || kind === 'webp-to-jpg') ? 'image/jpeg' : file.type; setOut(c.toDataURL(type, quality / 100)); }; im.src = src; }
  function download() { if (!out) return; const a = document.createElement('a'); a.href = out; a.download = 'image-processed.' + (kind === 'jpg-to-png' ? 'png' : kind === 'image-to-base64' ? 'txt' : 'jpg'); a.click(); }
  if (!file) return <div className="workspace"><div className="privacy">🔒 Your image stays on your device. Processing happens directly in your browser.</div><div className="dropzone" onClick={() => input.current?.click()} onDrop={e => { e.preventDefault(); load(e.dataTransfer.files[0]); }} onDragOver={e => e.preventDefault()}><Upload size={40}/><h3>Drop your image here</h3><p className="muted">or click to browse • JPG, PNG, WebP</p><input ref={input} hidden type="file" accept="image/*" onChange={e => e.target.files && load(e.target.files[0])}/></div></div>;
  return <div className="workspace"><div className="privacy">🔒 Processing happens locally in your browser — no server upload.</div><div className="workspaceGrid"><div><img className="preview" src={out || src} alt="Image preview"/><div className="statsLine"><span>{file.name}</span><span>{width} × {height}px</span><span>{(file.size / 1024).toFixed(1)} KB</span></div><button className="button secondary" onClick={() => { setFile(null); setSrc(''); setOut(''); }}><RotateCcw size={16}/> Reset</button></div><div className="controls"><label>Width</label><input type="number" value={width} onChange={e => setWidth(Number(e.target.value))}/><label>Height</label><input type="number" value={height} onChange={e => setHeight(Number(e.target.value))}/><label>Quality: {quality}%</label><input type="range" min="1" max="100" value={quality} onChange={e => setQuality(Number(e.target.value))}/>{kind === 'image-to-base64' && <textarea rows={7} readOnly value={out}/>}<button className="button primary" onClick={process}>Process Image <Download size={17}/></button>{out && <button className="button primary" style={{marginLeft:8}} onClick={download}><Download size={17}/> Download</button>}</div></div></div>;
}
