import type { Metadata } from 'next';
import Link from 'next/link';
import AdPlaceholder from '../components/AdPlaceholder';
import BackgroundRemoverTool from './BackgroundRemoverTool';

export const metadata: Metadata = { title: { absolute: 'Free Image Background Remover Online | Image Resizer Tools' }, description: 'Remove image backgrounds online for free. Create transparent images or replace backgrounds with colors, gradients or your own image.', alternates: { canonical: '/background-remover' }, openGraph: { title: 'Free Image Background Remover Online | Image Resizer Tools', description: 'Remove image backgrounds locally in your browser.' } };
const related = [['Image Compressor','/image-compressor'],['Image Resizer','/image-resizer'],['JPG to PNG','/jpg-to-png'],['PNG to JPG','/png-to-jpg'],['WebP to JPG','/webp-to-jpg'],['Image Cropper','/image-cropper'],['Image to Base64','/image-to-base64'],['Favicon Generator','/favicon-generator']];
export default function BackgroundRemoverPage() { return <main className="toolPage"><div className="container"><div className="crumb"><Link href="/">Home</Link> <span>›</span> Image Tools <span>›</span> Background Remover</div><h1>Free Image Background Remover</h1><p className="muted">Remove backgrounds from images and create transparent PNGs or replace the background with a color, gradient or another image.</p><BackgroundRemoverTool/><AdPlaceholder /><article className="content"><h2>What Is an Image Background Remover?</h2><p>A background remover separates the main subject from the rest of a photo, creating a transparent cutout that can be used in designs, product pages and social graphics.</p><h2>How to Remove an Image Background</h2><p>Upload a JPG, PNG or WebP, then choose Remove Background. The segmentation model loads only when needed and runs in your browser. The transparent result appears in a clean preview ready for editing.</p><h2>How the Background Editor Works</h2><p>Keep the checkerboard transparency, pick a solid color, build a gradient, or upload another image. Use the simple sliders to adjust the subject and background before downloading.</p><h2>Transparent vs Colored Backgrounds</h2><p>Transparent PNGs are useful when the image needs to sit on different surfaces. JPG does not support transparency, so choose a color, gradient or image before exporting to JPG.</p><h2>Supported Image Formats</h2><p>JPG, PNG and WebP uploads are supported. PNG is recommended for transparent output; JPG and WebP offer adjustable quality for compositions with a background.</p><AdPlaceholder /><h2>Frequently Asked Questions</h2><div className="faq">{[['Is the background remover free?','Yes. The tool is free to use and does not require an account.'],['Can I download a transparent PNG?','Yes. Keep Transparent selected and download PNG.'],['Can I add a new background?','Yes. Choose a color, gradient or upload your own background image.'],['Does it work on mobile?','Yes. The upload, editor controls and editor controls are touch-friendly.'],['Are my images uploaded to a server?','The removal model and composition run locally in your browser; images are not normally uploaded to our server.'],['Why can some images be harder to process?','Low contrast, busy edges, hair and unusual subjects can be harder for segmentation models to separate.']].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div><AdPlaceholder /><h2>More Free Image Tools</h2><div className="related">{related.map(([n,u])=><Link className="pill" href={u} key={u}>{n}</Link>)}</div></article></div></main> }

