import type {Metadata} from 'next'; import Link from 'next/link';
const articles:any={
 'how-to-compress-an-image':{title:'How to Compress an Image Without Losing Too Much Quality',intro:'Compression makes an image file smaller by changing how its visual data is stored. The goal is not the smallest possible file; it is a useful balance between clarity and weight.',heads:[['Start with the right format','Photographs usually compress well as JPG or WebP. Logos, screenshots and images that need transparency are often better as PNG.'],['Adjust quality gradually','Start at a medium or high quality, compare the result at the size it will actually be displayed, and reduce quality only when the file is still too large.'],['Use the compressor','Upload an image to the Image Compressor, choose a quality level and compare the output size before downloading. Keep the original so you can try again.']],tool:'/image-compressor'},
 'how-to-resize-an-image-online':{title:'How to Resize an Image Online',intro:'Resizing changes an image’s pixel dimensions. It is useful when a site asks for a specific width, height or aspect ratio.',heads:[['Preserve the aspect ratio','Lock the ratio when you want the image to stay natural. Enter exact dimensions only when the destination requires them.'],['Choose a display size','A large image shown in a small card can slow loading. Resize close to the largest size the page needs.'],['Download a purposeful format','Use JPG or WebP for many photos and PNG where transparency or crisp flat graphics matter.']],tool:'/image-resizer'},
 'jpg-vs-png':{title:'JPG vs PNG: Which Image Format Should You Use?',intro:'JPG and PNG solve different problems. JPG is usually compact for photographs, while PNG keeps transparency and sharp edges.',heads:[['Choose JPG for photos','JPG uses lossy compression, which can make a photograph much smaller. It is a practical choice for banners, portraits and camera images.'],['Choose PNG for transparency','PNG is useful for logos, interface screenshots and graphics that need transparent pixels or crisp lines.'],['Convert when needed','Use JPG to PNG when transparency or lossless-style edges matter, and PNG to JPG when a smaller, broadly supported photo file is more useful.']],tool:'/jpg-to-png'},
 'webp-vs-jpg':{title:'WebP vs JPG: What’s the Difference?',intro:'WebP is a modern image format that can provide smaller files at similar visual quality. JPG remains widely supported and easy to share.',heads:[['WebP for modern sites','WebP can be a strong default for web pages where smaller transfers matter and the browser supports it.'],['JPG for compatibility','JPG is familiar across editing tools, uploads and older workflows. It is often the safer interchange format.'],['Test the real image','Image content matters. Compare the result at its actual display size instead of choosing a format by file extension alone.']],tool:'/webp-to-jpg'},
 'reduce-image-to-100kb':{title:'How to Reduce an Image to 100KB',intro:'A 100KB limit is a target, not a promise that every image can reach it without visible tradeoffs. Photos with detail may need smaller dimensions as well as lower quality.',heads:[['Resize first','Reducing unnecessary pixel dimensions often saves more space than aggressively lowering quality.'],['Compress and check','Use the compressor, download the result and check the actual file size. Repeat with a smaller dimension or lower quality if needed.'],['Keep expectations realistic','Flat graphics and simple photos are easier to reduce than detailed images, textures or screenshots with text.']],tool:'/image-compressor'},
 'reduce-image-to-50kb':{title:'How to Reduce an Image to 50KB',intro:'Very small upload limits require deliberate choices about dimensions, format and quality.',heads:[['Use a compact source','A photo with fewer pixels gives the encoder less data to store. Start by resizing it to the display size.'],['Prefer the right format','JPG or WebP often works for photos. PNG may be necessary for transparency but can be larger.'],['Review readability','Do not optimize only for the number. Check faces, text and edges after every change.']],tool:'/image-compressor'},
 'what-is-image-compression':{title:'What Is Image Compression?',intro:'Image compression reduces the number of bytes needed to store or transmit an image. It does not always change the pixel dimensions.',heads:[['Lossy and lossless','Lossy compression discards some visual information to save more space. Lossless compression preserves the image data but may produce a larger file.'],['Quality and size trade off','Higher quality generally means a larger output. The right setting depends on where the image will be used.'],['Compression is not resizing','A large image can still be large after compression. Resizing and compression often work best together.']],tool:'/image-compressor'},
 'how-to-create-a-favicon':{title:'How to Create a Favicon for a Website',intro:'A favicon is the small icon shown in browser tabs, bookmarks and shortcuts. A simple, high-contrast source usually works best at tiny sizes.',heads:[['Start with a clear mark','Avoid fine details that disappear at 16×16 pixels. A recognizable symbol or letter is easier to read.'],['Generate common sizes','Use Favicon Generator to prepare browser, Apple and Android icon sizes from your source.'],['Test at real size','Preview the 16×16 and 32×32 versions. An icon that looks good large may need simplification when reduced.']],tool:'/favicon-generator'},
 'image-size-and-loading-speed':{title:'How Image Size Affects Website Loading Speed',intro:'Images can be one of the largest parts of a page transfer. Smaller, correctly sized assets can improve the time before a page feels useful.',heads:[['Avoid oversized assets','Do not serve a 4000px image when the layout displays it at 800px. Resize close to the largest needed display size.'],['Choose an efficient format','JPG and WebP can make photographs substantially smaller. PNG remains useful for transparency and graphics.'],['Measure the real page','Compression helps, but layout, fonts, scripts and network conditions also affect loading. Treat image optimization as one part of the whole page.']],tool:'/image-resizer'},
 'how-to-remove-a-background':{title:'How to Remove a Background From an Image',intro:'Background removal separates a subject from surrounding pixels and produces a transparent result that can be placed on a new surface.',heads:[['Use a clear source','Good contrast between subject and background generally gives automatic segmentation more information to work with.'],['Review the edges','Hair, transparent objects and busy backgrounds can be difficult. Zoom in and check the result before publishing.'],['Edit the result','Background Remover can keep transparency or place the subject over a color, gradient or uploaded image.']],tool:'/background-remover'}
};
export async function generateStaticParams(){return Object.keys(articles).map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const article=articles[slug];return {title:article?.title||'Image Guide',description:article?.intro||'Practical image guide from Image Resizer Tools.'}}
export default async function Article({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const a=articles[slug];if(!a)return <main className="toolPage"><div className="container content"><h1>Guide not found</h1><Link href="/blog">Back to guides</Link></div></main>;return <main className="toolPage"><article className="container content"><div className="crumb"><Link href="/">Home</Link> <span>›</span> <Link href="/blog">Blog</Link> <span>›</span> {a.title}</div><h1>{a.title}</h1><p>{a.intro}</p>{a.heads.map(([h,p]:string[])=><section key={h}><h2>{h}</h2><p>{p}</p></section>)}<p><Link className="button primary" href={a.tool}>Try the related tool →</Link></p></article></main>}
